Update generate-github-commit-history-browser-link.yml

diff --git a/.github/workflows/generate-github-commit-history-browser-link.yml b/.github/workflows/generate-github-commit-history-browser-link.yml
--- a/.github/workflows/generate-github-commit-history-browser-link.yml
+++ b/.github/workflows/generate-github-commit-history-browser-link.yml
@@ -37,6 +37,7 @@ jobs:
           BRANCH: ${{ github.event.inputs.branch }}
           SINCE_REF: ${{ github.event.inputs.since-ref }}
         run: |
+          set-failed() { printf "::error::$1\n" "${@:2}" ; exit 123 ; }
           REPO="${REPO//[[:space:]]/}"
           if [[ "$REPO" =~ ^https://github.com/ ]]; then
             REPO="${REPO#https://github.com/}"
@@ -52,12 +53,14 @@ jobs:
           fi
           BRANCH="${BRANCH//[[:space:]]/}"
           SINCE_REF="${SINCE_REF//[[:space:]]/}"
+          [[ -z "$REPO" ]] && set-failed "No repo input provided."
+          [[ -z "$BRANCH" ]] && set-failed "No repo input provided."
           if [[ ! "$REPO" =~ ^[a-zA-Z0-9_.-]+\/[a-zA-Z0-9_.-]+$ ]]; then
-            printf "::error::Invalid repo format. Please check the input value: '%s'\n" "$REPO"
+            set-failed "Invalid repo format. Please check the input value: '%s'" "$REPO"
             exit 1
           fi
           if [[ ! "$BRANCH" =~ ^[a-zA-Z0-9_./-]+$ ]]; then
-            printf "::error::Invalid branch format. Please check the input value: '%s'\n" "$BRANCH"
+            set-failed "Invalid branch format. Please check the input value: '%s'" "$BRANCH"
             exit 1
           fi
           printf "REPO=%s\n" "$REPO" >> $GITHUB_ENV
